name: "cachix"
on:
  push:
  pull_request:
    branches:
      - update_flake_lock_action
jobs:
  nixos-unstable:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@v1.3.1
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: niri
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build packages and push to cachix
      run: nix build .#checks.x86_64-linux.cached-packages