name: "cachix"
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: niri
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build niri-stable and niri-unstable; push to cachix
      run: nix-store --query --requisites $(nix-store --query --deriver $(nix build --print-out-paths .#niri-stable .#niri-unstable)) | cachix push niri