name: "cachix"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: niri
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#niri-stable .#niri-unstable
    - run: nix-store --query --requisites $(nix-store --query --deriver $(nix eval --raw .#niri-stable)) | cachix push niri
    - run: nix-store --query --requisites $(nix-store --query --deriver $(nix eval --raw .#niri-unstable)) | cachix push niri