name: "check"
on:
  push:
  pull_request:
jobs:
  fmt:
    name: "nix fmt"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix fmt $(find ./ -regex './[^.]*\.nix') -- --check
  check:
    name: "nix flake check"
    runs-on: ubuntu-latest
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@v1.3.1
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: niri
    - run: nix flake check
  check-docs:
    name: "generated docs match"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: niri
    - run: |
        # note: docs really do exceed the default call depth limit. as a workaround, increase it.
        export NIX_CONFIG="max-call-depth = 20000"

        nix eval --raw .#lib.internal.docs-markdown > docs.fresh.md

        # this to print the full docs in the logs so we can easier see what's going on
        cat docs.fresh.md
        cat docs.md

        diff docs.md docs.fresh.md
