name: Update flake.lock
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Hourly. We want it to run frequently.

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v20
        with:
          token: '${{ secrets.UPDATE_TOKEN }}'
          pr-title: "Update flake.lock"
          pr-body: |
            Automated changes by the [update-flake-lock](https://github.com/DeterminateSystems/update-flake-lock) GitHub Action.
            
            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```
          pr-labels: |
            dependencies
            automated